# Generated by Django 3.0.2 on 2020-02-05 13:56

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preceptores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('CPF', models.CharField(max_length=15, unique=True)),
                ('CRM_RN', models.PositiveIntegerField(default=0, unique=True)),
                ('data_nascimento', models.DateField()),
                ('RG', models.CharField(max_length=10, unique=True)),
                ('emissor_RG', models.CharField(max_length=50)),
                ('UF_RG', models.CharField(choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Distrito Federal', 'DF'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO')], default='', max_length=30)),
                ('endereço', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('CEP', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=100)),
                ('UF_CEP', models.CharField(choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Distrito Federal', 'DF'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO')], default='', max_length=30)),
                ('telefone', models.CharField(max_length=20)),
                ('celular_1', models.CharField(blank=True, max_length=20)),
                ('celular_2', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('banco', models.CharField(max_length=50)),
                ('angencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=30)),
                ('escolaridade', multiselectfield.db.fields.MultiSelectField(choices=[('Graduação', 'GRADUACAO'), ('Residência', 'RESIDENCIA'), ('Mestrado', 'MESTRADO'), ('Doutorado', 'DOUTORADO')], default='', max_length=39)),
                ('num_edital', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo_Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores')),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('data_termino', models.DateField()),
                ('instituicao', models.CharField(max_length=50)),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores')),
            ],
        ),
        migrations.CreateModel(
            name='Mestrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('data_termino', models.DateField()),
                ('instituicao', models.CharField(max_length=50)),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores')),
            ],
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
                ('data_termino', models.DateField()),
                ('instituicao', models.CharField(max_length=50)),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores')),
            ],
        ),
        migrations.CreateModel(
            name='Doutorado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('data_termino', models.DateField()),
                ('instituicao', models.CharField(max_length=50)),
                ('preceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores')),
            ],
        ),
    ]
