# Generated by Django 3.0.2 on 2020-03-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preceptores',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
