# Generated by Django 3.0.2 on 2020-03-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doutorado',
            name='d_ano_termino',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doutorado',
            name='d_area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mestrado',
            name='m_ano_termino',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mestrado',
            name='m_area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='r_ano_termino',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='r_area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='r_instituicao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
