# Generated by Django 3.0.2 on 2020-03-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doutorado',
            name='d_preceptores',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores'),
        ),
        migrations.AlterField(
            model_name='mestrado',
            name='m_preceptores',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='r_preceptores',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores'),
        ),
    ]
