# Generated by Django 3.0.2 on 2020-03-11 12:03

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoProfissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', multiselectfield.db.fields.MultiSelectField(choices=[('SESAP-HRC', ' SECRETARIA DE ESTADO DA SAÚDE PÚBLICA – HOSPITAL REGIONAL DE CAICÓ'), ('SESAP-HRMC', 'SECRETARIA DE ESTADO DA SAÚDE PÚBLICA – HOSPITAL REGIONAL MARIANO COELHO'), ('SESAP-HGT', 'SECRETARIA DE ESTADO DA SAÚDE PÚBLICA – HOSPITAL GISELDA TRIGUEIRO'), ('SESAP-HMWG', 'SECRETARIA DE ESTADO DA SAÚDE PÚBLICA – HOSPITAL MONSENHOR WALFREDO GURGEL'), ('SESAP-OUTRO', 'SECRETARIA DE ESTADO DA SAÚDE PÚBLICA – OUTRO:'), ('SMS-CAICO', 'SECRETARIA MUNICIPAL DE SAÚDE DE CAICÓ'), ('SMS-CURRAIS_NOVOS', 'SECRETARIA MUNICIPAL DE SAÚDE DE CURRAIS NOVOS'), ('SMS-SANTA_CRUZ', 'SECRETARIA MUNICIPAL DE SAÚDE DE SANTA CRUZ'), ('OUTRO', 'OUTRO')], max_length=102)),
                ('sesap_outro', models.CharField(blank=True, max_length=100, null=True)),
                ('outro_vinculo', models.CharField(blank=True, max_length=100, null=True)),
                ('preceptores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores')),
            ],
        ),
    ]
