# Generated by Django 3.0.2 on 2020-02-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doutorado',
            old_name='preceptor',
            new_name='preceptores',
        ),
        migrations.RenameField(
            model_name='graduacao',
            old_name='preceptor',
            new_name='preceptores',
        ),
        migrations.RenameField(
            model_name='mestrado',
            old_name='preceptor',
            new_name='preceptores',
        ),
        migrations.RenameField(
            model_name='residencia',
            old_name='preceptor',
            new_name='preceptores',
        ),
        migrations.RenameField(
            model_name='vinculo_profissional',
            old_name='preceptor',
            new_name='preceptores',
        ),
    ]
