# Generated by Django 3.0.2 on 2020-01-29 19:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preceptores',
            name='escolaridade',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Graduação', 'GRADUACAO'), ('Residência', 'RESIDENCIA'), ('Mestrado', 'MESTRADO'), ('Doutorado', 'DOUTORADO')], default='', max_length=39),
        ),
    ]
