# Generated by Django 3.0.2 on 2020-03-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0002_auto_20200304_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doutorado',
            name='d_instituicao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
