# Generated by Django 3.0.2 on 2020-03-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0002_auto_20200305_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doutorado',
            name='d_ano_termino',
            field=models.PositiveIntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='g_ano_termino',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='g_curso',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mestrado',
            name='m_ano_termino',
            field=models.PositiveIntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='r_ano_termino',
            field=models.PositiveIntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='r_preceptores',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores'),
        ),
    ]
