# Generated by Django 3.0.2 on 2020-03-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0002_vinculoprofissional'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VinculoProfissional',
            new_name='Vinculo_Profissional',
        ),
    ]
