# Generated by Django 3.0.2 on 2020-03-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0003_auto_20200311_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinculo_profissional',
            old_name='preceptores',
            new_name='v_preceptores',
        ),
        migrations.AlterField(
            model_name='preceptores',
            name='CRM_RN',
            field=models.PositiveIntegerField(default='', unique=True),
        ),
    ]
