# Generated by Django 3.0.2 on 2020-03-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0004_auto_20200304_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mestrado',
            name='m_instituicao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
