# Generated by Django 3.0.2 on 2020-03-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0006_auto_20200304_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mestrado',
            name='preceptores',
        ),
        migrations.RemoveField(
            model_name='residencia',
            name='preceptores',
        ),
        migrations.RemoveField(
            model_name='vinculo_profissional',
            name='preceptores',
        ),
        migrations.DeleteModel(
            name='Doutorado',
        ),
        migrations.DeleteModel(
            name='Mestrado',
        ),
        migrations.DeleteModel(
            name='Residencia',
        ),
        migrations.DeleteModel(
            name='Vinculo_Profissional',
        ),
    ]
