# Generated by Django 3.0.2 on 2020-03-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0007_auto_20200304_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graduacao',
        ),
    ]
