# Generated by Django 3.0.2 on 2020-03-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0008_delete_graduacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preceptores',
            name='num_edital',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
