# Generated by Django 3.0.2 on 2020-03-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0009_auto_20200304_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo_Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preceptores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores')),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_area', models.CharField(blank=True, max_length=50)),
                ('r_ano_termino', models.PositiveIntegerField(blank=True, default=0, null=True, unique=True)),
                ('r_instituicao', models.CharField(blank=True, max_length=50)),
                ('preceptores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores')),
            ],
        ),
        migrations.CreateModel(
            name='Mestrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_area', models.CharField(blank=True, max_length=50)),
                ('m_ano_termino', models.PositiveIntegerField(blank=True, default=0, null=True, unique=True)),
                ('m_instituicao', models.CharField(blank=True, max_length=50)),
                ('preceptores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores')),
            ],
        ),
        migrations.CreateModel(
            name='Graduacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_curso', models.CharField(max_length=50)),
                ('g_ano_termino', models.PositiveIntegerField(default=0, unique=True)),
                ('g_instituicao', models.CharField(max_length=50)),
                ('preceptores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores')),
            ],
        ),
        migrations.CreateModel(
            name='Doutorado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_area', models.CharField(blank=True, max_length=50)),
                ('d_ano_termino', models.PositiveIntegerField(blank=True, default=0, null=True, unique=True)),
                ('d_instituicao', models.CharField(blank=True, max_length=50)),
                ('preceptores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preceptores.Preceptores')),
            ],
        ),
    ]
