# Generated by Django 3.0.2 on 2020-03-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preceptores', '0010_doutorado_graduacao_mestrado_residencia_vinculo_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculo_profissional',
            name='preceptores',
        ),
        migrations.RemoveField(
            model_name='doutorado',
            name='preceptores',
        ),
        migrations.RemoveField(
            model_name='graduacao',
            name='preceptores',
        ),
        migrations.RemoveField(
            model_name='mestrado',
            name='preceptores',
        ),
        migrations.RemoveField(
            model_name='residencia',
            name='preceptores',
        ),
        migrations.AlterField(
            model_name='doutorado',
            name='d_ano_termino',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='graduacao',
            name='g_ano_termino',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mestrado',
            name='m_ano_termino',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='r_ano_termino',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Preceptores',
        ),
        migrations.DeleteModel(
            name='Vinculo_Profissional',
        ),
    ]
